name: molb 
channels:
  - rdkit
  - defaults
dependencies:
  - matplotlib=3.0.3
  - pandas=1.1.5
  - pip=19.1.1
  - python=3.6.8
  - rdkit=2019.03.3.0
  - pip:
    - h5py==2.9.0
    - keras==2.2.0
    - numpy==1.16.3
    - scikit-learn==0.20.3
    - seaborn==0.9.0
    - tensorflow==1.5.0
    - chembl-webresource-client==0.10.3
    - requests-cache==0.6.4
